puppetlabs/ace

config/transport_tasks_config.rb

Part of the PE installation testing is verifying that the ACE service is restricted to the whitelisted addresses.
Without the ACL then these tests would fail and the service would be reachable from outside of the PE infrastructure.
Statement/Question: We could alternatively reuse the BoltServer::ACL class?

(FM-7872) adding in the acls for the ace service

---

lib/ace/transport_app.rb
spec/unit/ace/transport_app_spec.rb

To keep the debug endpoints the same across products, this adds a few
from bolt-server.

(maint) additional admin endpoints from bolt-server

---

.rubocop.yml
config/docker.conf
config/local.conf
config/transport_tasks_config.rb
lib/ace/client/catalog.rb
lib/ace/config.rb
lib/ace/plugin_cache.rb
lib/ace/transport_app.rb
spec/Dockerfile
spec/fixtures/api_server_configs/global-ace-server.conf
spec/fixtures/api_server_configs/required-ace-server.conf
spec/fixtures/conf/auth.conf
spec/unit/ace/client/catalog_spec.rb
spec/unit/ace/config_spec.rb
spec/unit/ace/plugin_cache_spec.rb
spec/unit/ace/transport_app_spec.rb

Example of what would be passed to the endpoint at https://0.0.0.0:44633/execute_catalog
```json
{
"target":{
"remote-transport":"panos",
"host":"bt642as8dm1z0fo.delivery.puppetlabs.net",
"user":"admin",
"password":"admin"
},
"compiler":{
"certname":"bt642as8dm1z0fo.delivery.puppetlabs.net",
"environment":"production",
"transaction_uuid":"981687ce-520e-11e9-8647-d663bd873d93",
"job_id":"1"
}
}
```

(FM-7882) Add client for catalog retrieval

---

developer-docs/docker.md
spec/fixtures/conf/auth.conf

Also adds some notes for linux users when using the compose for testing.

(FM-7952) allow reports from ACE in testing auth.conf

---

.gitignore
developer-docs/api.md
lib/ace/transport_app.rb
spec/unit/ace/transport_app_spec.rb

Parse device details obtained from the catalog endpoint, and create a NetworkDevice instance

(FM-7886) Catalog execution - transport endpoint

---

lib/ace/transport_app.rb
spec/unit/ace/transport_app_spec.rb

Changes introduced in Bolt https://github.com/puppetlabs/bolt/commit/77690441e1f5655b824dfc653b07cbf5beb9861f caused this to break. 
In flight system test will prevent this from going unnoticed.

(maint) remove load_config parameter

---

Dockerfile
config/docker.conf
developer-docs/docker.md

Since the execution of catalogs requires Puppet configuration, the original base image did not have the required dependencies and initialisation was failing.
This change extends the puppet-agent alpine image and runs the ACE service on top in order to ensure the relevant dependencies are met.
Part of this change also required updating of the certificate requirements for working both within a container and `locally`, which means existing container users will need to regenerate new certs and restart the puppetserver,
```
cd spec/
docker-compose up -d --build --force-recreate
```
Instructions on regenerating the cert has been added to the docker.md file in developer-docs.

(maint) fixing up the docker setup for executing catalogs

---

developer-docs/docker.md

Previously it talked about the ACE container being the first container to get running, this however is invalid as the relevant certs would not be available to the service and would cause issues.

(maint) making it clear on order of running the containers

---

README.md
developer-docs/docker.md
lib/ace/transport_app.rb
spec/acceptance/ace/transport_app_spec.rb
spec/unit/ace/transport_app_spec.rb

To facilitate a responsive UX, `/execute_catalog` should return the same status codes as https://github.com/puppetlabs/pxp-agent/blob/918eaed001d8a2098053ce344e8bb9381be4fe8e/modules/pxp-module-puppet#L204-L210
This change implements that by extracting the report from the `run` method and reformatting the results as required.

(PE-27024) return detailed results from `/execute_catalog`

---

lib/ace/schemas/ace-run_task.json
spec/unit/ace/transport_app_spec.rb

As it is legal for bolt to not use remote transports for tasks, we should
not require one here.

(FM-8446) remove remote-transport requirement

---

README.md

A minor formatting change to `README.md` to generate an arbitrary change and push the `v1.0.0` tag through the CI pipeline. See [QENG-7501](https://tickets.puppetlabs.com/browse/QENG-7501) for more details.

(QENG-7501) Minor formatting change to push tag in build pipeline

---

.rubocop.yml
lib/ace/transport_app.rb

With this commit, a puma status endpoint is added to our app.
(We already implement the gc_stats endpoint.)
Since this endpoint is served by our app, there will always be one
thread in use in the result: that thread is the status request itself.
This is not true with the default puma status endpoint,
as it runs within a separate server ... as per puma/lib/puma/runner.rb.

(PE-27794) add a puma status endpoint

---

lib/ace/transport_app.rb

The Task struct in bolt was refactored to be a proper class. Part of the refactor was changing the init method. This commit updates task instantiation to be compatible with the refactored class in Bolt. https://github.com/puppetlabs/bolt/commit/308405933786ed2c1becd9ea978fa67c76cf5dde#

(maint) Update Task constructor to follow new pattern in Bolt

---

.travis.yml
acceptance/.gitignore
acceptance/Gemfile
acceptance/Rakefile
acceptance/config/gem/options.rb
acceptance/config/git/options.rb
acceptance/config/package/options.rb
acceptance/lib/acceptance/ace_command_helper.rb
acceptance/lib/acceptance/ace_setup_helper.rb

This commit adds back the acceptance directory removed in https://github.com/puppetlabs/ace/pull/70 as our CI expects there to be such directory.

(maint) Restore acceptance shell

---

.travis.yml
agentless-catalog-executor.gemspec
lib/ace/transport_app.rb
spec/Dockerfile
spec/unit/ace/transport_app_spec.rb

This commit updates ace-server to reflect changes to the bolt `Result` object. This also fixes a bug in error creation whereby previously the `Target` we attempt to reference `name` for will always be the only element in an array, the `name` method was attempted to be called on the `Array`, this has been updated to call the method on the `Target`.

(PE-29007) Update to bolt > 2.9.0

---

config/transport_tasks_config.rb
spec/fixtures/api_server_configs/global-ace-server.conf
spec/unit/ace/config_spec.rb

This commit removes the `whitelist` references in ace-server and
replaces them with `allowlist`. This is part of the effort to remove
harmful terminology, and will configure ace to use the new `allowlist`
ace-server.conf key rather than the old key.

(PE-30044) Remove harmful terminology from ace

---

agentless-catalog-executor.gemspec

Given we control exactly what version of bolt is shipped with PE, leave the gemspec unbounded at the upper end to avoid pain around `x` bumps in the future.

(PE-31081) Open ended bolt dep

---

lib/ace/plugin_cache.rb
spec/unit/ace/plugin_cache_spec.rb

Previously we were configuing an http pool for pluginsync. The internal puppet client now handles this and pushing our own instance onto puppet's context is no longer needed.

(PE-31688) Remove unused, deprecated pattern

---

agentless-catalog-executor.gemspec

concurrent-ruby was locked to 1.1.5 in https://github.com/puppetlabs/ace/pull/69
due to an issue in 1.1.6. A fix for that was released
in concurrent-ruby-1.1.7: https://github.com/ruby-concurrency/concurrent-ruby/pull/856
Recently, in puppet-runtime, concurrent-ruby was
bumped to 1.1.8 https://github.com/puppetlabs/puppet-runtime/pull/446/files#diff-6393a204a090900f17b88f58f21f2b5c355271b5e8df85328a80accbc2c503e0R2
making ruby pe-ace-server unable to start:
```
-- Unit pe-ace-server.service has begun starting up.
May 17 08:15:28 main-wisdom puma[15711]: /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs’: Could not find ‘concurrent-ruby’ (= 1.1.5) - did find: [concurrent-ruby-1.1.8] (Gem::MissingSpecVersionError)
```
This commit removes the lock of …

(maint) remove concurrent-ruby lock

---

lib/ace/transport_app.rb

This was originally added as part of
https://github.com/puppetlabs/ace/pull/12 with no context behind the
addition. Turns out it is an unnecessary efficiency, so we revert back
to the previous behavior of just calling executor.run_task and having
the request-handling thread run the task. This is OK since the run_task
endpoint only takes in one target.
Signed-off-by: Enis Inan <enis.inan@puppet.com>

(PE-31689) Don't fork in run_task endpoint

---

lib/ace/transport_app.rb
spec/unit/ace/transport_app_spec.rb

In order for the task result to be used in a plan run from orchestrator, we need to unwrap the data in the response from bolt/ace server. Orchestrator takes care of obfuscating sensitive task results.

(PE-32027) Unwrap sensitive task results

---

Gemfile
agentless-catalog-executor.gemspec
lib/puppet/indirector/catalog/certless.rb
spec/unit/ace/plugin_cache_spec.rb
spec/unit/puppet/resource/catalog/certless_spec.rb

In a related body of work [1], a new method was added to the
Puppet::HTTP::Service::Compiler class to expose the v4 catalog
endpoint in puppetserver. This commit changes the catalog indirector
to use that new method to find certless catalogs.
[1]: https://github.com/puppetlabs/puppet/commit/c3800ff0b17fa56728f14e0e928aa7e64f535a1b

(PE-31686) use new v4 catalog endpoint

---

lib/ace/transport_app.rb

This ensures that they don't appear in the logs.
Signed-off-by: Enis Inan <enis.inan@puppet.com>

(PE-32470) Wrap sensitive parameters before calling Executor#run_task
